tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # Instal Wasmer and WAPM CLI
      # ------------------------------------
      sudo apt install libncurses5 libxkbcommon0 libtinfo5 libnss3-tools -y
      curl https://get.wasmer.io -sSfL | sh 
      source /home/gitpod/.wasmer/wasmer.sh
      sudo echo "source /home/gitpod/.wasmer/wasmer.sh" >> $HOME/.bashrc

      # ------------------------------------
      # Install Sat (Suborbital)
      # ------------------------------------
      git clone --depth=1 https://github.com/suborbital/sat.git
      cd sat
      go build -o .bin/sat -tags netgo,wasmtime .
      sudo cp .bin/sat /usr/local/bin/sat
      cd ..
      rm -rf sat

      # ------------------------------------
      # Install the Suborbital CLI
      # ------------------------------------
      brew tap suborbital/subo
      brew install subo

    init: |

      RELEASE="0.1.6"
      ARCHITECTURE="amd64"

      # ------------------------------------
      # Install Procyon
      # ------------------------------------

      wget https://github.com/bots-garden/procyon/releases/download/${RELEASE}/procyon-launcher-${RELEASE}-linux-${ARCHITECTURE}.tar.gz
      mkdir procyon-launcher
      tar -zxf procyon-launcher-${RELEASE}-linux-${ARCHITECTURE}.tar.gz --directory procyon-launcher
      
      cd procyon-launcher

      procyon_json="$(cat <<-EOF
      {
        "executors": {
          "satExecutorPath": "/usr/local/bin/sat"
        },  
        "functions": {
          "wasmFilesDirectory": "./functions"
        },
        "http":{
          "start": 3000
        }
      }
      EOF
      )"
      
      echo "${procyon_json}" > procyon-launcher.json


      # ------------------------------------
      # Install ProcyonCtl
      # ------------------------------------
      #procyonctl_config="$(cat <<-EOF
      #WASM_REGISTRY_URL="https://registry-cdn.wapm.io/contents"
      #PROCYON_URL="http://localhost:9090"
      #PROCYON_REVERSE_URL="http://localhost:8080"
      #EOF
      #)"

      procyonctl_config="$(cat <<-EOF
      WASM_REGISTRY_URL="https://localhost:7070/get"
      PROCYON_URL="http://localhost:9090"
      PROCYON_REVERSE_URL="http://localhost:8080"
      EOF  
      )"

      echo "${procyonctl_config}" > procyonctl.config

      sudo cp ./procyonctl /usr/local/bin/procyonctl
      sudo cp ./procyonctl.config /usr/local/bin/procyonctl.config

      rm ./procyonctl
      rm ./procyonctl.config

      cd ..



      echo "🎉 ready to discover Procyon 😃"

ports:
    # Alcor reverse proxy 
  - port: 8080
    visibility: public
    # Procyon
  - port: 9090
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - golang.go
    - grain-lang.vscode-grain
    - rust-lang.rust
