tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # Instal Wasmer and WAPM CLI
      # ------------------------------------
      sudo apt install libncurses5 libxkbcommon0 libtinfo5 libnss3-tools -y
      curl https://get.wasmer.io -sSfL | sh 
      source /home/gitpod/.wasmer/wasmer.sh
      sudo echo "source /home/gitpod/.wasmer/wasmer.sh" >> $HOME/.bashrc

      # ------------------------------------
      # Install Sat (Suborbital)
      # ------------------------------------
      git clone --depth=1 https://github.com/suborbital/sat.git
      cd sat
      go build -o .bin/sat -tags netgo,wasmtime .
      sudo cp .bin/sat /usr/local/bin/sat
      cd ..
      rm -rf sat

      # ------------------------------------
      # Install the Suborbital CLI
      # ------------------------------------
      brew tap suborbital/subo
      brew install subo

    init: |

      RELEASE="0.1.5"
      ARCHITECTURE="amd64"

      echo "🎉 ready to discover Procyon 😃"

ports:
    # Alcor reverse proxy 
  - port: 8080
    visibility: public
    # Procyon
  - port: 9090
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - golang.go
    - grain-lang.vscode-grain
    - rust-lang.rust

